version: "3.3"

services:
  db:
    image: postgres:13.3
    ports:
      - "5436:5436"
    volumes:
      - postgres:/var/lib/postgresql/test
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
volumes:
  postgres: {}
